package config

const (
	// ADAPTER ...
	ADAPTER = "mysql"
	// USERNAME ...
	USERNAME = "root"
	// PASSWORD ...
	PASSWORD = ""
	// DATABASE ...
	DATABASE = "atami_development"
	// CHARSET ...
	CHARSET = "utf8"
)
